/**
 * Specs Inc. 2026
 * PremadeQuestions.ts — baked trivia for the premade "cosmos" deck cards.
 *
 * The 37 premade cards in cardDeckData.ts never change, so their battle
 * questions are authored once here instead of being regenerated by an OpenAI
 * call every match. This makes premade questions instant, free, and reliable;
 * only the user-specific CAPTURED-card questions are generated at runtime.
 *
 * Shape matches BattleQuestionGenerator's GeneratedQuestion (minus id, which the
 * MultiplayerTriviaManager assigns at queue-assembly time), so the manager can
 * map these through the same toRecord() path. Correct-answer positions are
 * varied across 1-4 on purpose so players can't pattern-match a single slot.
 *
 * Difficulty is intentionally CASUAL / general-audience: each question keeps the
 * same fact as its card (cardDeckData.ts) but is phrased plainly, with clearly-
 * wrong distractors so most players can answer it. Because a question is shown
 * WITHOUT its card image, each one names its own subject up front (e.g. "the
 * artist Kuniyoshi", "an 'engawa' veranda") instead of saying "this artist" /
 * "this house" — it must read as fully self-contained. Each question carries BOTH
 * a `roast` (spoken on a wrong answer) and a `praise` (spoken on a correct one) —
 * short, witty, and specific to the fact, so the host's reaction always fits.
 */

export interface BakedQuestion {
  question: string;
  option1: string;
  option2: string;
  option3: string;
  option4: string;
  optionCount: number;
  answer: number; // 1-indexed correct option
  roast: string;  // wrong-answer line
  praise: string; // correct-answer line
}

export const PREMADE_QUESTIONS: BakedQuestion[] = [
  // --- Tokyo --------------------------------------------------------------
  {
    question: "The copper roofs on old Japanese shrines slowly turn green over the years. What famous statue gets its green color from that exact same process?",
    option1: "Michelangelo's David", option2: "The Lincoln Memorial", option3: "The Statue of Liberty", option4: "Mount Rushmore",
    optionCount: 4, answer: 3, roast: "Green with envy at the folks who got that one?", praise: "Correct — you've got an eye for green.",
  },
  {
    question: "Japan's cute 'kawaii' toy characters measurably changed over the 20th century to look more like what?",
    option1: "Babies — rounder and cuter", option2: "Robots", option3: "Wild animals", option4: "Serious adults",
    optionCount: 4, answer: 1, roast: "Too cute to focus? That one was a softball.", praise: "Spot on — and adorably so.",
  },
  {
    question: "The 1800s Japanese artist Kuniyoshi drew a famously accurate giant skeleton — because he had studied imported foreign books on what subject?",
    option1: "Cooking", option2: "Anatomy — the human body", option3: "Sailing", option4: "Music",
    optionCount: 4, answer: 2, roast: "Bone up before the next round.", praise: "Nailed it, right down to the bones.",
  },
  {
    question: "Old Japanese homes have an 'engawa' — a raised wooden veranda under deep eaves — that keeps the house cool in summer with no machines. How does it work?",
    option1: "Buried blocks of ice", option2: "Gold-leaf mirrors", option3: "Shade plus natural airflow underneath", option4: "Hidden electric fans",
    optionCount: 4, answer: 3, roast: "No amount of airflow saves that one.", praise: "Cool, calm, and correct.",
  },
  {
    question: "Japan's famous 'sabo' engineering — barriers built across mountain rivers — was developed mainly to protect people from what?",
    option1: "Earthquakes", option2: "Wildfires", option3: "Tornadoes", option4: "Floods and landslides",
    optionCount: 4, answer: 4, roast: "That answer washed clean away.", praise: "Correct — that knowledge really holds water.",
  },
  {
    question: "Calm spaces like Japanese Zen gardens are being studied to help design better living quarters for whom?",
    option1: "Astronauts on long space missions", option2: "Pro athletes", option3: "Train drivers", option4: "Restaurant chefs",
    optionCount: 4, answer: 1, roast: "Go find your zen — and a better guess.", praise: "Correct — very zen of you.",
  },
  {
    question: "Japanese brush calligraphy is surprisingly hard to do aboard a spacecraft. Why?",
    option1: "The paper dissolves", option2: "Astronauts can't see the page", option3: "Without gravity, the ink won't flow down the brush normally", option4: "Brushes are banned on the station",
    optionCount: 4, answer: 3, roast: "Your answer floated off into orbit.", praise: "Correct — that answer really flows.",
  },
  {
    question: "An ice skater glides on a thin film of water on top of the ice. What mostly creates that water?",
    option1: "Friction from the moving blade", option2: "The skater's body heat", option3: "Salt spread on the ice", option4: "Warm air in the rink",
    optionCount: 4, answer: 1, roast: "You slipped right off the podium.", praise: "Correct — smooth as fresh ice.",
  },
  {
    question: "Japan turned cute local animals, like the fluffy little shimaenaga bird, into what?",
    option1: "Protected zoo-only animals", option2: "Branded regional mascots and merchandise", option3: "National house pets", option4: "Official postage stamps only",
    optionCount: 4, answer: 2, roast: "Even the fluffy bird is side-eyeing you.", praise: "Correct — the fluffy bird approves.",
  },
  {
    question: "Instantly seeing a 'face' in two dots and a line — like on a cute toy — is a brain trick called what?",
    option1: "Déjà vu", option2: "Pareidolia", option3: "Hypnosis", option4: "Color blindness",
    optionCount: 4, answer: 2, roast: "I can see the face you're making at that score.", praise: "Correct — I can see you smiling.",
  },
  {
    question: "A Japanese company invented a special instant version of which food so astronauts could eat it on the Space Shuttle?",
    option1: "Sushi", option2: "Tempura", option3: "Ramen", option4: "Mochi",
    optionCount: 4, answer: 3, roast: "That guess never made it to orbit.", praise: "Correct — cooked to perfection, even in space.",
  },
  {
    question: "Nearly every train station in Tokyo plays its own short, distinctive what, so commuters recognize their stop?",
    option1: "Musical jingle", option2: "Weather report", option3: "Comedy clip", option4: "Loud alarm bell",
    optionCount: 4, answer: 1, roast: "That's your cue to exit — wrong stop.", praise: "Correct — right on cue.",
  },
  {
    question: "The bumpy yellow 'tactile paving' on sidewalks feels springy because it's made of rubber, which comes from the sap of what?",
    option1: "An oak tree", option2: "Bamboo", option3: "A rubber tree", option4: "A cactus",
    optionCount: 4, answer: 3, roast: "You bounced clean off that one.", praise: "Correct — you bounced right to it.",
  },
  {
    question: "Japanese train stations sell little regional clay figurines mainly as what?",
    option1: "Travel souvenirs and gifts", option2: "Children's playthings", option3: "Good-luck charms only", option4: "Religious statues",
    optionCount: 4, answer: 1, roast: "No souvenir for that guess.", praise: "Correct — take a souvenir.",
  },
  {
    question: "What did scientists finally confirm in 2024 about orange tabby cats?",
    option1: "They are usually female", option2: "They cannot see the color orange", option3: "Their orange color comes from one special gene", option4: "They are all closely related",
    optionCount: 4, answer: 3, roast: "That was a cat-astrophe.", praise: "Correct — purr-fectly done.",
  },
  {
    question: "What is 'yarn-bombing,' sometimes seen brightening up train stations and street poles?",
    option1: "A speed-knitting contest", option2: "Covering public objects in colorful crochet", option3: "A type of spray graffiti", option4: "A new kind of commuter train",
    optionCount: 4, answer: 2, roast: "You dropped a stitch there.", praise: "Correct — not a stitch out of place.",
  },
  {
    question: "Some Japanese shrines are modernizing the omikuji — the little paper fortune you draw at random. How?",
    option1: "Banning it entirely", option2: "Only letting priests read it aloud", option3: "Handing it out by app, vending machine, or robot", option4: "Doubling its price",
    optionCount: 4, answer: 3, roast: "Today's omikuji predicted that answer.", praise: "Correct — fortune favors you today.",
  },
  {
    question: "Japan's tiny 'kei' cars get great gas mileage around the city mainly because they are what?",
    option1: "Small and lightweight", option2: "Fully electric", option3: "Powered by huge engines", option4: "Driven very slowly",
    optionCount: 4, answer: 1, roast: "Running on empty with that one.", praise: "Correct — running on pure efficiency.",
  },
  {
    question: "Airlines and Japanese canned-coffee makers both add extra sugar to their drinks. Why?",
    option1: "Sugar is cheaper to use", option2: "Changes in pressure and temperature dull our sense of taste", option3: "Customers loudly demand it", option4: "Sugar keeps the drink colder",
    optionCount: 4, answer: 2, roast: "That guess left a bitter aftertaste.", praise: "Correct — sweet, sweet victory.",
  },
  {
    question: "Airline meals are seasoned more heavily than normal food. What does an airplane cabin's pressure do to your sense of taste?",
    option1: "Makes everything taste salty", option2: "Sharpens it", option3: "Weakens it by about a third", option4: "Has no effect at all",
    optionCount: 4, answer: 3, roast: "Even airplane food has more taste than that guess.", praise: "Correct — that one had real flavor.",
  },

  // --- Seattle ------------------------------------------------------------
  {
    question: "The baked beans now standard in a full English breakfast were first sold in Britain as what?",
    option1: "A cheap wartime ration", option2: "A fancy luxury import", option3: "A new health food", option4: "Cattle feed",
    optionCount: 4, answer: 2, roast: "You don't know beans about this.", praise: "Correct — now you know your beans.",
  },
  {
    question: "Seattle's Burke-Gilman Trail, used for biking and walking, was paved right on top of an old what?",
    option1: "Railroad line", option2: "Shipping canal", option3: "Airport runway", option4: "Riverbed",
    optionCount: 4, answer: 1, roast: "That answer went right off the rails.", praise: "Correct — right on track.",
  },
  {
    question: "A corgi's famously short legs come from a gene that also gives which other breed its stubby legs?",
    option1: "The Great Dane", option2: "The greyhound", option3: "The poodle", option4: "The dachshund",
    optionCount: 4, answer: 4, roast: "Short legs, even shorter on the answer.", praise: "Correct — a big-brain answer on tiny legs.",
  },
  {
    question: "Seattle-area glass artist Dale Chihuly stopped blowing glass himself after a 1976 car crash caused him to lose what?",
    option1: "His studio", option2: "An eye, and his depth perception", option3: "His hearing", option4: "His memory",
    optionCount: 4, answer: 2, roast: "Didn't see that one coming either.", praise: "Correct — sharp eye, fittingly.",
  },
  {
    question: "The trendy fiddle-leaf fig houseplant is actually what kind of plant out in the wild?",
    option1: "A desert cactus", option2: "A floating water plant", option3: "A 'strangler' that grows over and kills other trees", option4: "A low carpet of moss",
    optionCount: 4, answer: 3, roast: "Your guess got strangled — very on brand.", praise: "Correct — you didn't get strangled.",
  },
  {
    question: "A fish looking straight up sees the entire world above the water squeezed into what?",
    option1: "A bright circle overhead", option2: "A long rainbow", option3: "Total darkness", option4: "An upside-down mirror in every direction",
    optionCount: 4, answer: 1, roast: "Your view of that one was a little cloudy.", praise: "Correct — crystal-clear view.",
  },
  {
    question: "Wild gourds were once so bitter that only which giant animals would eat them and spread their seeds?",
    option1: "Dinosaurs", option2: "Ice Age giants like mastodons", option3: "Sea turtles", option4: "Giant birds",
    optionCount: 4, answer: 2, roast: "That answer's extinct too.", praise: "Correct — that knowledge isn't extinct.",
  },
  {
    question: "When you watch the sun set over Seattle's Puget Sound, it has technically already dropped below the horizon. Why can you still see it?",
    option1: "It's just a reflection on the water", option2: "The air bends its light up and over to you", option3: "Your eyes simply lag behind", option4: "City lights are faking it",
    optionCount: 4, answer: 2, roast: "Your answer set two minutes ago.", praise: "Correct — you saw right through it.",
  },
  {
    question: "Scientists bolted lichens to the outside of the space station for about 18 months. What happened to them?",
    option1: "They burned up", option2: "They crumbled to dust", option3: "They survived and kept living once back on Earth", option4: "They mutated into animals",
    optionCount: 4, answer: 3, roast: "Even space lichen outlasted that guess.", praise: "Correct — out-of-this-world answer.",
  },
  {
    question: "In traditional Japanese mochi pounding, two people keep a steady chant and rhythm going. Why?",
    option1: "So the heavy mallet never smashes the other person's hand", option2: "To attract a crowd", option3: "Purely for good luck", option4: "To cook the rice faster",
    optionCount: 4, answer: 1, roast: "You got pounded on that one.", praise: "Correct — perfect timing.",
  },
  {
    question: "Seattle legend says the view through a ring-shaped sculpture in Volunteer Park inspired the title of which 1994 hit song?",
    option1: "'Smells Like Teen Spirit'", option2: "'Jeremy'", option3: "'Alive'", option4: "'Black Hole Sun'",
    optionCount: 4, answer: 4, roast: "That answer? Black hole. Gone.", praise: "Correct — that one was a hit.",
  },
  {
    question: "The term 'flying saucer' was coined in 1947 after a pilot reported strange objects near which Washington State mountain?",
    option1: "Mount Rainier", option2: "Mount Fuji", option3: "Mount Everest", option4: "The Rocky Mountains",
    optionCount: 4, answer: 1, roast: "Your answer's the real UFO.", praise: "Correct — no UFO needed.",
  },
  {
    question: "Why can a vintage camping gas-lantern mantle still set off a Geiger counter decades later?",
    option1: "It's coated in lead paint", option2: "It's slightly radioactive", option3: "It's full of leftover gas", option4: "It's made of magnetized steel",
    optionCount: 4, answer: 2, roast: "That answer's radioactive — and wrong.", praise: "Correct — that answer glows.",
  },
  {
    question: "Bending a single piece of wire into the shape of a figure, as sculptor Alexander Calder did, is nicknamed what?",
    option1: "'Drawing in space'", option2: "'Cold welding'", option3: "'Iron lacework'", option4: "'Line painting'",
    optionCount: 4, answer: 1, roast: "You just drew a blank.", praise: "Correct — you drew that one perfectly.",
  },
  {
    question: "The first-ever Little Free Library was built in 2009 by a man honoring his late mother, who had been a what?",
    option1: "A librarian", option2: "A teacher", option3: "A novelist", option4: "A carpenter",
    optionCount: 4, answer: 2, roast: "Return that answer — it's overdue.", praise: "Correct — no late fees for you.",
  },
  {
    question: "Why do Seattle's ornamental cherry trees all burst into bloom at almost exactly the same time?",
    option1: "They share the same rich soil", option2: "They are all the same age", option3: "A warm spring rain triggers them", option4: "They're all clones of one single tree",
    optionCount: 4, answer: 4, roast: "That answer never blossomed.", praise: "Correct — that answer blossomed.",
  },
  {
    question: "Some smart plush toys come alive in augmented reality when you point a phone camera at them. This mix of physical toy and digital world is nicknamed what?",
    option1: "'Phygital'", option2: "'Wi-Fi toys'", option3: "'Cloud pets'", option4: "'Robo-dolls'",
    optionCount: 4, answer: 1, roast: "That guess wasn't very 'phygital.'", praise: "Correct — very phygital of you.",
  },
];
